# s4 spider
XEN_URL:r8a779h0 = "git://github.com/xen-troops/xen.git;protocol=https;branch=spider-master"
XEN_REL:r8a779h0 = "4.17"
XEN_REV:r8a779h0 = "8711910a8fb66eb454172a9e6427aaf62bfc3a80"

# v4h whitehawk
XEN_URL:r8a779g0 = "git://github.com/xen-troops/xen.git;protocol=https;branch=xen-4.19-xt0.2_v4h_demo"
XEN_REL:r8a779g0 = "4.19"
XEN_REV:r8a779g0 = "${AUTOREV}"
LIC_FILES_CHKSUM:r8a779g0 = "file://COPYING;md5=d1a1e216f80b6d8da95fec897d0dbec9"
